#animations list file - loads in all of the animations into a list
import pygame, os
file_dir = os.getcwd()

animationsRightPlayer = [pygame.image.load(f"{file_dir}/textures/jim/R1.png"), pygame.image.load(f"{file_dir}/textures/jim/R2.png"), pygame.image.load(f"{file_dir}/textures/jim/R3.png"), pygame.image.load(f"{file_dir}/textures/jim/R4.png"), pygame.image.load(f"{file_dir}/textures/jim/R5.png"), pygame.image.load(f"{file_dir}/textures/jim/R6.png"), pygame.image.load(f"{file_dir}/textures/jim/R7.png"), pygame.image.load(f"{file_dir}/textures/jim/R8.png"), pygame.image.load(f"{file_dir}/textures/jim/R9.png")]
animationsLeftPlayer = [pygame.image.load(f"{file_dir}/textures/jim/L1.png"), pygame.image.load(f"{file_dir}/textures/jim/L2.png"), pygame.image.load(f"{file_dir}/textures/jim/L3.png"), pygame.image.load(f"{file_dir}/textures/jim/L4.png"), pygame.image.load(f"{file_dir}/textures/jim/L5.png"), pygame.image.load(f"{file_dir}/textures/jim/L6.png"), pygame.image.load(f"{file_dir}/textures/jim/L7.png"), pygame.image.load(f"{file_dir}/textures/jim/L8.png"), pygame.image.load(f"{file_dir}/textures/jim/L9.png")]

animationsRightEnemy = [pygame.image.load(f"{file_dir}/textures/billy/R1E.png"), pygame.image.load(f"{file_dir}/textures/billy/R2E.png"), pygame.image.load(f"{file_dir}/textures/billy/R3E.png"), pygame.image.load(f"{file_dir}/textures/billy/R4E.png"), pygame.image.load(f"{file_dir}/textures/billy/R5E.png"), pygame.image.load(f"{file_dir}/textures/billy/R6E.png"), pygame.image.load(f"{file_dir}/textures/billy/R7E.png"), pygame.image.load(f"{file_dir}/textures/billy/R8E.png"), pygame.image.load(f"{file_dir}/textures/billy/R9E.png"), pygame.image.load(f"{file_dir}/textures/billy/R10E.png"), pygame.image.load(f"{file_dir}/textures/billy/R11E.png")]
animationsLeftEnemy = [pygame.image.load(f"{file_dir}/textures/billy/L1E.png"), pygame.image.load(f"{file_dir}/textures/billy/L2E.png"), pygame.image.load(f"{file_dir}/textures/billy/L3E.png"), pygame.image.load(f"{file_dir}/textures/billy/L4E.png"), pygame.image.load(f"{file_dir}/textures/billy/L5E.png"), pygame.image.load(f"{file_dir}/textures/billy/L6E.png"), pygame.image.load(f"{file_dir}/textures/billy/L7E.png"), pygame.image.load(f"{file_dir}/textures/billy/L8E.png"), pygame.image.load(f"{file_dir}/textures/billy/L9E.png"), pygame.image.load(f"{file_dir}/textures/billy/L10E.png"), pygame.image.load(f"{file_dir}/textures/billy/L11E.png")]
